services:
  form-php:
    restart: always
    image: docker.box:5000/blind-openings-form-php:latest
    environment:
      X_MAL_CLIENT_ID: ${X_MAL_CLIENT_ID}
      DB_HOST: form-db
      DB_USER: ${DB_FORM_USER}
      DB_PASS: ${DB_FORM_PASS}
      DB_NAME: ${DB_FORM_NAME}
      API_KEY: ${API_KEY}
    depends_on:
      - form-db
  form-db:
    restart: always
    image: mariadb:12-noble
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: ${DB_FORM_USER}
      MARIADB_PASSWORD: ${DB_FORM_PASS}
      MARIADB_DATABASE: ${DB_FORM_NAME}
    volumes:
      - form_db_data:/var/lib/mysql
  form-web:
    restart: always
    image: docker.box:5000/blind-openings-form-web:latest
    ports:
      - "${PORT_FORM_WEB}:80"
  panel-php:
    restart: always
    image: docker.box:5000/blind-openings-panel-php:latest
    environment:
      DB_HOST: panel-db
      DB_USER: ${DB_PANEL_USER}
      DB_PASS: ${DB_PANEL_PASS}
      DB_NAME: ${DB_PANEL_NAME}
      FORM_API: ${FORM_API}
      API_KEY: ${API_KEY}
    volumes:
      - "${VIDEO_DIR}:/video:ro"
    depends_on:
      - panel-db
  panel-db:
    restart: always
    image: mariadb:12-noble
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: ${DB_PANEL_USER}
      MARIADB_PASSWORD: ${DB_PANEL_PASS}
      MARIADB_DATABASE: ${DB_PANEL_NAME}
    volumes:
      - panel_db_data:/var/lib/mysql
  panel-web:
    restart: always
    image: docker.box:5000/blind-openings-panel-web:latest
    ports:
      - "${PORT_PANEL_WEB}:80"
    volumes:
      - "${VIDEO_DIR}:/videos:ro"
      - "${IMAGE_DIR}:/images:ro"
volumes:
  form_db_data:
  panel_db_data:
