services:
  php:
    restart: always
    image: docker.box:5000/blind-openings-php:latest
    environment:
      X_MAL_CLIENT_ID: ${X_MAL_CLIENT_ID}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
  db:
    restart: always
    image: mariadb:12-noble
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
  panel-php:
    restart: always
    image: docker.box:5000/blind-openings-panel-php:latest
    environment:
      DB_HOST: panel-db
      DB_USER: ${DB_PANEL_USER}
      DB_PASS: ${DB_PANEL_PASS}
      DB_NAME: ${DB_PANEL_NAME}
      API_LISTS: ${API_LISTS}
    volumes:
      - "${VIDEO_DIR}:/video:ro"
    depends_on:
      - panel-db
  panel-db:
    restart: always
    image: mariadb:12-noble
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: ${DB_PANEL_USER}
      MARIADB_PASSWORD: ${DB_PANEL_PASS}
      MARIADB_DATABASE: ${DB_PANEL_NAME}
    volumes:
      - panel_db_data:/var/lib/mysql
  web:
    restart: always
    image: docker.box:5000/blind-openings-web:latest
    ports:
      - "2137:80"
  panel-web:
    restart: always
    image: docker.box:5000/blind-openings-panel-web:latest
    ports:
      - "2138:80"
    volumes:
      - "${VIDEO_DIR}:/videos:ro"
      - "${IMAGE_DIR}:/images:ro"
volumes:
  db_data:
  panel_db_data:
